[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "combmodel"
authors = [{name = "Luiz G. A. Alves", email = "lgaalves@northwestern.edu"}]
dynamic = ["version", "description"]